spring.application.name=knowyourfan
spring.datasource.url=jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:6543/postgres?user=postgres.bgtybauglcryyezqzryw&password=Furiaintern123

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.tool.hbm2ddl=DEBUG
spring.jpa.properties.hibernate.default_schema=public

twitter.consumer.key=2qDqx7VXtq5s5BDDRWWzL4TJF
twitter.consumer.secret=PKZiztB4BDqDeTZuQyvCMohKfxodurprDUXJsJK8eQcg7Pes0I
twitter.access.token=dldsSFdyOHNsdXdGdDhCWkxZdG86MTpjaQ
twitter.access.token.secret=Rv2mHTlahlHEGCqOzWvZ2Lqzp6yoRmbGCoyb8D3MV8tDOUyU_T
