spring.application.name=knowyourfan
spring.datasource.url=jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:6543/postgres?user=postgres.bgtybauglcryyezqzryw&password=Furiaintern123

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.tool.hbm2ddl=DEBUG
spring.jpa.properties.hibernate.default_schema=public


twitter.bearer-token=AAAAAAAAAAAAAAAAAAAAAL1A0wEAAAAAmjUGU8%2BzxlJpu4LuSuhx09goxrA%3DFL3mvAosOF2zRbxwtPhnPM7x2Qx2Y20hztJclJ11deAwi4XsKs
